plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vipfh666.xianmo'
    compileSdk 34

    defaultConfig {
        applicationId "com.vipfh666.xianmo"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
